# Generated by Django 5.1.7 on 2025-04-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Soil_Moisture', models.BigIntegerField(max_length=150, verbose_name='Soil Moisture')),
                ('Temperature', models.BigIntegerField(max_length=150, verbose_name='Temperature')),
                ('Soil_Humidity', models.BigIntegerField(max_length=255, verbose_name='Soil Humidity')),
                ('Air_temperature', models.FloatField(max_length=255, verbose_name='Air temperature ?')),
                ('Air_humidity', models.FloatField(max_length=255, verbose_name='Air humidity (%)')),
                ('Pressure', models.FloatField(max_length=255, verbose_name='Pressure (KPa)')),
                ('ph', models.FloatField(max_length=255, verbose_name='ph')),
                ('rainfall', models.FloatField(max_length=255, verbose_name='rainfall')),
                ('Status', models.BigIntegerField(max_length=100, verbose_name='Status')),
            ],
        ),
    ]
