# Generated by Django 5.1.7 on 2025-04-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='Air_temperature',
            field=models.FloatField(max_length=255, verbose_name='Air temperature (C)'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='Soil_Humidity',
            field=models.IntegerField(verbose_name='Soil Humidity'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='Soil_Moisture',
            field=models.IntegerField(verbose_name='Soil Moisture'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='Status',
            field=models.IntegerField(verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='Temperature',
            field=models.IntegerField(verbose_name='Temperature'),
        ),
    ]
