# Generated by Django 5.1.7 on 2025-04-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0002_alter_plant_air_temperature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='Air_humidity',
            field=models.FloatField(verbose_name='Air humidity (%)'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='Air_temperature',
            field=models.FloatField(verbose_name='Air temperature (C)'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='Pressure',
            field=models.FloatField(verbose_name='Pressure (KPa)'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='ph',
            field=models.FloatField(verbose_name='ph'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='rainfall',
            field=models.FloatField(verbose_name='rainfall'),
        ),
    ]
